### ISSUE TITLE
Buffalo WI-U3-1200AX2(/N) Supports

### ISSUE THREAD

**Issue by makotosakuraijp** [lwfinger/rtl8852au#1]
Dear members,

I purchased the USB NIC Buffalo WI-U3-1200AX2 that was released last week. (And it is not listed as a supported device at the README.)

The vender does not disclose the driver details, but the Windows 11 driver filename implies that this is the Realtek 8852AU chipset. (lsusb -v says it is certainly a Realtek chipset.)

I compiled (on the latest Ubuntu) the rtw89(-usb) and rtl8852au projects. I tried in the latest kernel from the kernel.org. I did the lsmod, dmesg | grep, and modprobe.

It is like

[ 2323.390085] usbcore: registered new interface driver rtwifi_usb
[ 4548.632564] usbcore: deregistering interface driver rtwifi_usb
[ 5262.492451] usbcore: registered new interface driver rtl8852au.

but the WiFi adapter did not appear at the iwconfig. (Another Buffalo WiFi NIC appears when it is plugged.)

Is it yet to be supported by this project? Or, does it just mean the rtl8852au, which is not used in lsmod, must be supported by another project (or something else)?

Best,

Makoto Sakurai

**Comment by lwfinger** [comment]
Your Buffalo device is not yet in the tables, as I was unaware of it. Furthermore, As you did not provide the USB IDs, I still am not sure what needs to be added to the table. Please provide that line of the lsusb command.

The RTL8852AU chip should be supported by in-kernel driver rtw89 eventually, and I am working full-time to that end; however, I cannot tell when, or if, that will happen.

As soon as you send me the UsB IDs for your device, I will add it to the rtl8852au repo (this one). As I do not have one for testing, I have no idea if it will work.

**Comment by makotosakuraijp** [comment]
# lsusb

Bus 003 Device 002: ID 0411:0312 BUFFALO INC. (formerly MelCo., Inc.) 802.11ax WLAN Adapter

# lsusb -v

Bus 003 Device 002: ID 0411:0312 BUFFALO INC. (formerly MelCo., Inc.) 802.11ax WLAN Adapter
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0411 BUFFALO INC. (formerly MelCo., Inc.)
  idProduct          0x0312 
  bcdDevice            0.00
  iManufacturer           1 Realtek
  iProduct                2 802.11ax WLAN Adapter
  iSerial                 3 00e04c000001
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x004a
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           8
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol    255 Vendor Specific Protocol
      iInterface              2 802.11ax WLAN Adapter
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x05  EP 5 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x06  EP 6 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x07  EP 7 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x09  EP 9 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x0a  EP 10 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x0b  EP 11 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x0c  EP 12 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

I hope it works.

**Comment by lwfinger** [comment]
Thanks for the USB ID. Your device is now added to the tables in the rtl8852au repo.

**Comment by lwfinger** [comment]
By way of information, I was able to find this device on Japanese sites only. It cells for ~5,400 Yen, which is about $48 US or 42 Euro. If it comes to Europe or the US at those prices, it will be a good buy for a 2x2 device.

**Comment by makotosakuraijp** [comment]
# gedit rtl8852au/os_dep/linux/usb_intf.c

I changed VENDOR to VENDER for the BUFFALO. It worked fine. Thanks!

About the price, it is a good device although the connection is sometimes unstable under Windows 11's client manager. Buffalo and IO-DATA are good companies of Japan. I hope they continue good works. (I sometimes use ASUS as well, but this time was Buffalo for me.)

**Comment by lwfinger** [comment]
I changed VENDER to VENDOR everywhere. That way when it gets spelled correctly, it will not be wrong.

I have not tested the Windows driver, but the Linux version was quite stable for me. Of course, I am under the best of conditions using the 5G band, and about 1 m from the AP.

I expected that it would work for you. The chip seems sound and certainly works well in the PCIe implementation, although that implementation does seem to test the BIOS pretty severely. My 7-year old Toshiba laptop has passed the test, but not some new Lenovo and HP models.
