### ISSUE TITLE
Just thank you !

### ISSUE THREAD

**Issue by pmoreaux** [lwfinger/rtl8852au#11]
Dear Larry
Running OpenSUSE Leap  15.14.21 (on 2022-07-29) on HP Probook 6470b (a 10 years old laptop)
I compiled your code and it works fine with my USB key D-Link D-Link DWA-X1850 S (WiFi 6).
Well, the blue LED don't flash but this is not a problem!

Many thanks for your work !

Patrice Moreaux (from France)

**Comment by ostwind** [comment]
Larry is a high impact developer! Thanks from me as well. I Installed a QGOO AX1800 for linux. 

Small non-issue for anyone searching issues: 

during the make sign install step, if you run into an OpenSSL error regarding a file not found in ../crypto/, the command seemed to work despite the error. (MOK screen came up on reboot, and everything worked fine).

**Comment by biopsin** [comment]
Thank you Larry, 
successfully built for ASUS USB-AX56, voidlinux_5.18.19-x86_64-glibc 
([template](https://github.com/biopsin/voidpkg/tree/master/rtl8852au-dkms) for void)

**Comment by lwfinger** [comment]
Thank you.
