### ISSUE TITLE
cant install on raspberry pi running retropie

### ISSUE THREAD

**Issue by m1m1k4tz** [lwfinger/rtl8852au#15]
hi im trying to get my wifi 6 usb adapter to work on retropie but when i try to compile it i get an error but it works when i do ARCH=arm make but then it wont install it gives me the error install: cannot stat '8852au.ko': No such file or directory

**Comment by m1m1k4tz** [comment]
actually i got it to compile and install i was missing a package and it worked after another git pull so ARCH=arm make fixes it for raspberry pis

**Comment by m4ri01** [comment]
Hello @m1m1k4tz do you mind to share the step for compiling this library? when i try to run make command, i get this error:  
`#rm -f .symvers.8852au
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.15.70-v7l+/build M=/home/pi/rtl8852au  modules
make[1]: *** /lib/modules/5.15.70-v7l+/build: No such file or directory.  Stop.
make: *** [Makefile:639: modules] Error 2`  

Thank you

**Comment by lwfinger** [comment]
You have not installed thee kernel headers.This step depends on your distro. If you do a 'git pull', you will see how to do this for a number of distros.
