### ISSUE TITLE
does not work with Linux 5.4.0-126-generic #141-Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by Michael-RealT** [lwfinger/rtl8852au#16]
Hello, 
first of all thank you for the work that allows me to use my Asus AX56 Wifi USB key.

Apart from some details it worked well on the lower kernels 5.4.0-126-generic, with the latter I can not make the USB key work (currently to work, I boot with the kernel 5.4.0-125-generic)

In the marginal problems, the operation led does not light up.
I can't get it to boot directly in Wifi mode, it always starts with the internal disk unmounted, I have to eject it to get Wifi
This key is USB3, but I have to make it work on my self powered usb2 hub, on the self powered USB3 hub it doesn't seem to work, and on the direct ports of the PC, it works only a few minutes, probably due to a lack of current provided by the motherboard.

I'm not an expert in hardware configuration and debugging, but I'm willing to help you improve your code.
Please let me know if I can give you some logs to find out what could be wrong.

Bus 001 Device 011: ID 0b05:1997 ASUSTek Computer, Inc. USB2.0 Hub

**Comment by Michael-RealT** [comment]
here is the output of the "dmesg | tail -50" command when I plug the key into the USB3 hub
`[ 1899.354987] usb 8-2.1.1: new high-speed USB device number 4 using xhci_hcd
[ 1899.465117] usb 8-2.1.1: New USB device found, idVendor=0bda, idProduct=1a2b, bcdDevice= 0.00
[ 1899.465124] usb 8-2.1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 1899.465128] usb 8-2.1.1: Product: DISK
[ 1899.465131] usb 8-2.1.1: Manufacturer: Realtek
[ 1899.465832] usb-storage 8-2.1.1:1.0: USB Mass Storage device detected
[ 1899.466095] scsi host11: usb-storage 8-2.1.1:1.0
[ 1900.479486] scsi 11:0:0:0: Direct-Access     RTK      Driver Storage   2.00 PQ: 0 ANSI: 0 CCS
[ 1900.479844] sd 11:0:0:0: Attached scsi generic sg10 type 0
[ 1900.480125] sd 11:0:0:0: [sdk] 261760 512-byte logical blocks: (134 MB/128 MiB)
[ 1900.480345] sd 11:0:0:0: [sdk] Write Protect is on
[ 1900.480349] sd 11:0:0:0: [sdk] Mode Sense: 03 00 80 00
[ 1900.480519] sd 11:0:0:0: [sdk] No Caching mode page found
[ 1900.480524] sd 11:0:0:0: [sdk] Assuming drive cache: write through
[ 1900.524327]  sdk:
[ 1900.552097] sd 11:0:0:0: [sdk] Attached SCSI removable disk
[ 1907.679187] usb 8-2.1.1: reset high-speed USB device number 4 using xhci_hcd
[ 1912.855180] usb 8-2.1.1: device descriptor read/64, error -110
[ 1928.467433] usb 8-2.1.1: device descriptor read/64, error -110
[ 1928.655444] usb 8-2.1.1: reset high-speed USB device number 4 using xhci_hcd
[ 1933.847531] usb 8-2.1.1: device descriptor read/64, error -110
[ 1949.455800] usb 8-2.1.1: device descriptor read/64, error -110
[ 1949.651819] usb 8-2.1.1: reset high-speed USB device number 4 using xhci_hcd
[ 1949.672345] usb 8-2.1.1: device firmware changed
[ 1949.673119] usb 8-2.1.1: USB disconnect, device number 4
[ 1949.831792] usb 8-2.1.1: new high-speed USB device number 5 using xhci_hcd
[ 1949.934336] usb 8-2.1.1: New USB device found, idVendor=0b05, idProduct=1997, bcdDevice= 0.00
[ 1949.934340] usb 8-2.1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1949.934341] usb 8-2.1.1: Product: 802.11ac WLAN Adapter
[ 1949.934343] usb 8-2.1.1: Manufacturer: Realtek
[ 1949.934344] usb 8-2.1.1: SerialNumber: 00e04c000001
[ 1951.115384] rtl8852au 8-2.1.1:1.0 wlx04421a4daf7e: renamed from wlan0
[ 1963.992030] IPv6: ADDRCONF(NETDEV_CHANGE): wlx04421a4daf7e: link becomes ready
[ 1976.067040] xhci_hcd 0000:02:00.0: ERROR Transfer event TRB DMA ptr not part of current TD ep_index 17 comp_code 1
[ 1976.067046] xhci_hcd 0000:02:00.0: Looking for event-dma 00000002a72679c0 trb-start 00000002a72679b0 trb-end 00000002a72679b0 seg-start 00000002a7267000 seg-end 00000002a7267ff0
[ 1976.098054] xhci_hcd 0000:02:00.0: ERROR Transfer event TRB DMA ptr not part of current TD ep_index 17 comp_code 1
[ 1976.098060] xhci_hcd 0000:02:00.0: Looking for event-dma 00000002a72679d0 trb-start 00000002a72679b0 trb-end 00000002a72679b0 seg-start 00000002a7267000 seg-end 00000002a7267ff0
[ 1976.244198] xhci_hcd 0000:02:00.0: ERROR Transfer event TRB DMA ptr not part of current TD ep_index 17 comp_code 1
[ 1976.244207] xhci_hcd 0000:02:00.0: Looking for event-dma 00000002a72679e0 trb-start 00000002a72679b0 trb-end 00000002a72679b0 seg-start 00000002a7267000 seg-end 00000002a7267ff0
`
I can see the key connected and I have the ip when I do an "ifconfig", but if I ping or open an internet browser I can't access the internet

**Comment by lwfinger** [comment]
As you can see from your log at time 1899.465117, the device first presents itself as a USB disk with ID 0bda:1a28. On this disk is the Windows driver. That way they do not need to provide a CD, and that way they can handle computers without an optical drive.

Linux ignores this "disk" and disconnects it at time 1949.673119. At that point, the USB ID is 0b05:1997, which is the wifi device. All is correct until time 1976.067040 where there is an error transferring data.

The problem in booting with this dongle inserted is that your BIOS is set to boot a USB device first, before booting from the system disk. As such, it tries to boot the pseudo-disk and is failing. That you can change in your BIOS setup.

I also understand why a USB3 hub would not work with a USB2 port. I have not tested the device with USB2 ports or hubs. My computer has USB3 ports. I have also not tested on any external USB3 hubs.

I do not know why the data transfer error happens, or even what changed between kernel 5.4.0-125-generic and kernel 5.4.0-126-generic. As a rule, I do not deal with kernels this old. The current kernel is 5.19, and 6.0 will probably be released this weekend.

**Comment by MadMartian** [comment]
I have the same device and this works okay on kernel **5.4.0-144-generic** as at cb319bee1375ccf37eabe71dad6876a2894bb155.  I don't see any LED light on this thing either though.

![image](https://user-images.githubusercontent.com/2112359/226161923-444ded32-bd52-4b2e-a5e9-b4b72dbf91e1.png)
