### ISSUE TITLE
Cannot connect to satellite of mesh wifi system

### ISSUE THREAD

**Issue by nguyentran98** [lwfinger/rtl8852au#22]
Hi,

Thanks for your very useful project.
However, i have a problem when i try to connect to my Mesh system (ASUS ZenWifi Pro ET12) by usb wifi (ASUS USB-AX56). I can connect to the root node of Mesh system but it does not change automatically to the satellite node. I have tried to connect directly to the satellite node (at the corner where it is not covered by the root node) and it asked me to re-enter Wifi password even when the pw is correct but cannot connect. 
I have tried by a laptop and there are not any problems with wifi card integrated, but it does not work with USB-AX56. I have also tried on Windows with this laptop with USB-AX56 and the driver provided by ASUS. It worked without problems.
Please let me know if the driver is not supported yet for mesh wifi?

Thanks advance.

**Comment by lwfinger** [comment]
I have no idea. I did not write the driver, and I have no understanding of most of the 200,000 lines of code.

The Realtek group that wrote the driver is not one that I can ask questions. I do not have a mesh system. I do have an ax1500 router with mesh capabilities, but no satellite stations.

Is the router using WPA3 encryption? That may be the reason that the integrated wifi card cannot connect.

Unfortunately, this is all the information/suggestions that I can offer.
