### ISSUE TITLE
USB-AX56 Connects as USB 2.0

### ISSUE THREAD

**Issue by CrunchyDoodle** [lwfinger/rtl8852au#27]
I'm running ubuntu 20.04 LTS and was able to build the driver with "make -B" to force building with an error (now a warning) about using a GCC that was not exactly the one used to build the kernel. The driver was installed successfully. I plugged in an ASUS WiFi 6 AX1800 USB WiFi Adapter (USB-AX56), which was recognized. I used the standard WiFi setting dialog and was connected at 1200 Mb/s to my router. This works well.

My issue is that "lsusb -t -v" tells me the USB-AX56 is connected as USB 2.0 at 480M. I tried the other available USB 3.0 and 3.1 ports on my PC with the same result. Other USB 3.0 devices show up as USB 3.0 at 5000M and 10000M.  Since my ISP supplies 300 Mb/s of internet, it is not a real problem. However, I'm curious why the driver thinks it's a USB 2.0 device. Yes, I'm using the USB 3.0 cable that came with the USB-AX56.

**Comment by lwfinger** [comment]
With my device plugged directly inot a USB 3 post, 'lsusb -t -v' shows 

   |__ Port 13: Dev 3, If 0, Class=Wireless, Driver=btusb, 12M   ID 0bda:887b Realtek Semiconductor Corp. 

Note that this is with no driver loaded. The selection of USB speed is just between the USB device and the hub drivers. The wifi driver has nothing to do with that.

Are you sure of that  "USB 3" cable?

**Comment by CrunchyDoodle** [comment]
Thank you for taking the time to respond.

 

After posting my question and doing more research, I came upon a similar issue with a work-around solution:

 

You should create a file in /etc/modprobe.d called 88XXau.conf that looks similar to this to force USB 3.x operation. Without this file, the driver is supposed to come up and start in USB 2.x mode and switch up...

 

# Initial it will use USB2.0 mode which will limite 5G 11ac throughput

# (USB2.0 bandwidth only 480Mbps => throughput around 240Mbps)

# when modprobe add following options will let it switch to USB3.0 mode at initial driver

#

options 88XXau rtw_switch_usb_mode=1

#

#

#

## TODO: run time change usb2.0/3.0 mode

### usb2.0 => usb3.0

#```

# sudo sh -c "echo '1' > /sys/module/88XXau/parameters/rtw_switch_usb_mode"

#```

### usb3.0 => usb2.0

#```

# sudo sh -c "echo '2' > /sys/module/88XXau/parameters/rtw_switch_usb_mode"

 

With a minor adjustment to the name of your driver, I sent this command to the driver:

 

sudo sh -c "echo '1' > /sys/module/8852au/parameters/rtw_switch_usb_mode"

 

After unplugging and reinserting the device, I got this from lsusb -t -v:

 

    ID 1d6b:0003 Linux Foundation 3.0 root hub

    |__ Port 5: Dev 21, If 0, Class=Vendor Specific Class, Driver=rtl8852au, 5000M

        ID 0b05:1997 ASUSTek Computer, Inc.

 

 

I’m now getting the full internet speed as if I was plugged into my router with a cable.

 

My next step is to follow your instructions for a DKMS installation of the driver and add an appropriately modified version of the above file to /etc/modprobe.d.

 

Thanks again,

 

Bye.
