### ISSUE TITLE
getting a few errors on debian 11

### ISSUE THREAD

**Issue by wp-coin** [lwfinger/rtl8852au#30]
when I hit make I get

```
/bin/sh: 1: /usr/src/linux-headers-5.10.0-20-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.10.0-20-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.10.0-20-common/scripts/pahole-flags.sh: not found


```

however it did install in the right directory

```
insmod /lib/modules/5.10.0-20-amd64/kernel/drivers/net/wireless/realtek/rtw89/8852au.ko 

```

I am trying to make it work with USB-AX55 Nano

not sure if it is supported or not

here is the source code for windows driver 
https://www.asus.com/networking-iot-servers/adapters/all-series/usb-ax55-nano/helpdesk_download/?model2Name=USB-AX55-Nano

**Comment by lwfinger** [comment]
Tell me the output of 'lsusb'. That will tell if it is supported.

Those build warnings are not important.  I do not know which package has pahole-flags.sh.

**Comment by wp-coin** [comment]
Bus 005 Device 002: ID 0b05:1a62 ASUSTek Computer, Inc. 802.11ax WLAN Adapter

**Comment by wp-coin** [comment]
I added a line in /lib/udev/rules.d/40-usb_modeswitch.rules

```
# ASUSTek 802.11ax 55 nano WLAN Adapter
ATTR{idVendor}=="0b05", ATTR{idProduct}=="1a62", RUN+="usb_modeswitch '/%k'"

```

**Comment by wp-coin** [comment]
when I plugin an older 802.11n usb adapter it works but not the new 802.11ax

**Comment by lwfinger** [comment]
Get rid of that line you added to /lib/udev/rules.d/40-usb_modeswitch.rules. If you look at the lsusb line, it shows a wifi device, not a USB disk. It has already been mode switched.

I added your USB ID to the RTW8852AU table. Do a git pull, make, and sudo make install. The device should be recognized from then on.

The one thing that may happen is that your device might be an RTW8852BU. If that is the case, this driver will not work.

**Comment by wp-coin** [comment]
I have switched to Ubuntu and installed successfully

the chipset appears to be Realtek RTL8832BU

**Comment by lwfinger** [comment]
Does it work? I have no idea of the relationship between the 8832BU and any other of the Realtek chips.

**Comment by wp-coin** [comment]
I think I found the driver for RTL8852BU / RTL8832BU

https://www.zyxel.com/no/no/support/download?model=NWD7605

however, its giving me an error when trying to run install.sh

```
note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:297: /home/mason/Downloads/Linux/RTL8852BU_RTL8832BU_WiFi_linux_v1.15.7-112-g1d36f2f7.20211230/driver/rtl8852BU_WiFi_linux_v1.15.7-112-g1d36f2f7.20211227/os_dep/linux/recv_linux.o] Error 1
make[1]: *** [Makefile:1902: /home/mason/Downloads/Linux/RTL8852BU_RTL8832BU_WiFi_linux_v1.15.7-112-g1d36f2f7.20211230/driver/rtl8852BU_WiFi_linux_v1.15.7-112-g1d36f2f7.20211227] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-58-generic'
make: *** [Makefile:633: modules] Error 2
##################################################
Compile make driver error: 2
Please check error Mesg

```

**Comment by lwfinger** [comment]
Do you really expect me to fix the build errors for a driver that I have never seen, and certainly do not maintain? If I were interested in any consulting work, I would consider it, but I am not!

**Comment by wp-coin** [comment]
Never mind I fixed it myself, turns out c code and PHP are very much alike ;)
