### ISSUE TITLE
No interface speed information

### ISSUE THREAD

**Issue by moontide** [lwfinger/rtl8852au#31]
# Environments
 * OS: Fedora 37 x86_64
 * Kernel version: 6.1.7
 * WiFi dongle model: EDUP EP-AX1696GS
 * USB ID: 0bda:8832

# Desciption
The speed is 'unknown' in interface information of network manager applet.

And `cat /sys/class/net/$interface_name/speed` report error: `cat: /sys/class/net/wlp48s0f3u2/speed: Invalid argument`.

**Comment by lwfinger** [comment]
With all my wireless devices, I get the same. Only the wired interface shows a speed. It does not appear that the nl80211 subsystem does not set that parameter.
