### ISSUE TITLE
Fenvi FU-AX1800P netns

### ISSUE THREAD

**Issue by Killozor** [lwfinger/rtl8852au#39]
I'm using the Fenvi FU-AX1800P, no problem to install the driver.
But I can't set netns with iw, iw list doesn't report it capable.
If I understand well, it is more driver related than device related. Is there a way to make it netns capable?

**Comment by lwfinger** [comment]
Using netns would require a mac80211-based driver. This one is cfg80211 based. A driver for the USB cards (RTW8852AU, RTW8852BU, and RTW8852CU) will likely be written in the future, but I do not know how soon that will be.
