### ISSUE TITLE
TP-Link Archer TX20UH

### ISSUE THREAD

**Issue by TheFlipside** [lwfinger/rtl8852au#41]
Hello, I'm trying to get a TP-Link Archer TX20UH USB Adapater to work on my Fedora Linux 37, my current kernel version is 6.1.13-200.fc37.x86_64.

The adapter is recognised as

`Bus 004 Device 010: ID 2357:0141 TP-Link 802.11ac WLAN Adapter`

I can build the module as described and load it:

```
lsmod | grep 8852                                                                                                                                                       

8852au              13803520  0
cfg80211             1114112  6 mt76,8852au,mt76x02_lib,mac80211,mt76x02_usb,mt76x2_common
```

But I don't see the adapater as a new interface in "ip a" or "ifconfig -a".

I plugged it into a Windows machine and so I know it uses a virtual drive for the driver setup; do I need to do something in the "/lib/udev/rules.d/40-usb_modeswitch.rules" like it is needed for other models or what am I missing?

Relevant output of "lsusb -v": https://pastebin.com/Ud5N69uJ

**Comment by TheFlipside** [comment]
I think I figured it out.

In **rtl8852au/os_dep/linux/usb_intf.c** after line 164 I added

`{USB_DEVICE_AND_INTERFACE_INFO(USB_VENDOR_ID_TPLINK, 0x0141, 0xff, 0xff, 0xff), .driver_info = RTL8852A},`

and after rebuilding and loading the new module I now have the new interface as wlp1s0u1 and I can connect fine to my TP-Link EAP650-Wall Access Point; the adapater reports as Frequency: 5.58Ghz.
In the controller overview I see the client using "11axa (5 GHz)"

**Comment by lwfinger** [comment]
Yes, you did the correct fix. I have now made the change to the git repository. You should be able to do 'git checkout -f' and 'git pull'. After that, a 'make' and 'sudo make install' should allow your device to work.

**Comment by TheFlipside** [comment]
It's working fine after your instructions
