### ISSUE TITLE
led not working

### ISSUE THREAD

**Issue by georgnistor** [lwfinger/rtl8852au#42]
Hello all,

setting the lbkmode to 1 does not activate the LED
ex:  
sudo sh -c "echo '1' > /sys/module/8852au/parameters/rtw_lbkmode"

I have the D-Link DWA-ax1850.

**Comment by lwfinger** [comment]
The standard configuration does not turn on the LED.

See the line in include/autoconf.h that says /*#define CONFIG_RTW_LED*/. Remove the comments.

**Comment by georgnistor** [comment]
it is SOLVED
thanks
I set up the rtw_lbkmode=1
I have LED,
thanks @lwfinger

**Comment by LPascholatti** [comment]
This also helped me after months!
