### ISSUE TITLE
RTL8852AU driver for monitor mode ?

### ISSUE THREAD

**Issue by RobertChouKFC** [lwfinger/rtl8852au#51]
Hi All
It seems that the monitor mode of RTL8852AU with latest driver 1.15.0.1 on github not work properly on my Ubuntu(kernal 5.19),
Is there any updated driver for RTL8852 to use monitor mode?
Thanks for your answering.

**Comment by lwfinger** [comment]
The Realtek vendor drivers such as this one are supported only as far as getting them to build and run in station mode. If you want some other feature, you willl need to add it to the driver yourself. I do not know any more about the inner workings of the chip than you do.
I am working on preparing a driver to run under rtw89 that would support monitor and AP modes, but that effort is barely started.
