### ISSUE TITLE
USB-AX55-NANO does not enumerate a network device

### ISSUE THREAD

**Issue by klugja** [lwfinger/rtl8852au#54]
lsusb output:

`Bus 002 Device 009: ID 0b05:1a62 ASUSTek Computer, Inc. 802.11ax WLAN Adapter`

dmesg output:

```
[24247.309543] usb 2-12: new high-speed USB device number 9 using xhci_hcd
[24247.457975] usb 2-12: New USB device found, idVendor=0b05, idProduct=1a62, bcdDevice= 0.00
[24247.457978] usb 2-12: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[24247.457979] usb 2-12: Product: 802.11ax WLAN Adapter
[24247.457980] usb 2-12: Manufacturer: Realtek
[24247.457980] usb 2-12: SerialNumber: 00e04c000001
[24512.865086] ieee80211 phy0: rt2x00lib_rxdone_read_signal: Warning - Frame received with unrecognized signal, mode=0x0000, signal=0x0003, type=4
```
lsusb output:
```
$ lsmod | grep '8852au'
8852au              13492224  0
cfg80211              983040  1 8852au
usbcore               331776  14 xhci_hcd,ehci_pci,usbnet,8852au,snd_usb_audio,usbhid,snd_usbmidi_lib,cdc_mbim,cdc_ncm,cdc_wdm,uvcvideo,ehci_hcd,xhci_pci,cdc_ether
```
No wifi device in /sys:
```
jklug@jakDebian11:/sys/class/net$ ls
docker0  eno1  enp4s0  enx00e04c680b7a  lo
```
Comment for PID 1a62 (I have AX 55 not AX56):
```
/*=== ASUS USB-AX56 =======*/
{USB_DEVICE_AND_INTERFACE_INFO(USB_VENDOR_ID_ASUS, 0x1997, 0xff, 0xff, 0xff), .driver_info = RTL8852A},
{USB_DEVICE_AND_INTERFACE_INFO(USB_VENDOR_ID_ASUS, 0x1a62, 0xff, 0xff, 0xff), .driver_info = RTL8852A},
```

**Comment by lwfinger** [comment]
Apparently, the AX55 contains an 8852bu chip, which is the reason it is not working. I will send a message to my contact at Realtek to see is I can find a driver for 8852bu.

By the way, the commit message when your device was added to the 8852au driver was as follows:

commit 1bf2f7b392263090cc7a3c20111d06daa324d2f8
Author: Larry Finger <Larry.Finger@lwfinger.net>
Date:   Sat Jan 14 23:45:35 2023 -0600

    rtl8852au: Add ASUS device with ID of 0b05:1a62
    
    It is not known if this really is an RTW8852AU. If it is, this will work.
    
    Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>

We now know the answer to that implied question.

**Comment by lwfinger** [comment]
I got the driver from Realtek, and modified it to build through kernel 6.5. You should clone it from https://github/com/lwfinger/rtl8852b.git.

I hope it will work. Any problems with that driver should be discussed in a new issue under the new repo.
