### ISSUE TITLE
Network keeps disconnecting and asking for Auth

### ISSUE THREAD

**Issue by royweisfeld** [lwfinger/rtl8852au#57]
First off, thanks a ton for all of your hard an amazing work!
I am having trouble with constant disconnection and NetworkManager keeps asking me for the wifi password even though I have supplied and saved it.

System Info:
```
Kernel: 6.4.12-arch1-1
OS: EndeavourOS - 2023.02.08
```

journalctl -u wpa_supplicant.service -f error output:
```
wlan0: CTRL-EVENT-CONNECTED - Connection to XX:XX:XX:XX:XX:XX completed [id=0 id_str=]
bgscan simple: Failed to enable signal strength monitoring
MBO: Disable MBO/OCE due to misbehaving AP not having enabled PMF
wlan0: CTRL-EVENT-DISCONNECTED bssid=XX:XX:XX:XX:XX:XX reason=3 locally_generated=1
```

inxi -Fxza --no-host:
```
IF: enp4s0 state: down mac: <filter>
  Device-2: Realtek 802.11ax WLAN Adapter driver: rtl8852au type: USB
    rev: 2.0 speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 5-4:4 chip-ID: 0bda:885c
    class-ID: 0000 serial: <filter>
  IF: wlan0 state: up mac: <filter>
```

**Comment by lwfinger** [comment]
Run the command 'sudo dmesg > dmesg.txt' and attach dmesg.txt to this issue. That way I will see the reason for the disconnect.

**Comment by royweisfeld** [comment]
For some reason after a recent update that problem seemed to have gone away, probably a faulty update from about a month ago, sadly not sure what exactly cause the problem but thanks!
