### ISSUE TITLE
Periodic driver hang

### ISSUE THREAD

**Issue by hardening** [lwfinger/rtl8852au#70]
I've installed the driver for a `2001:3321 D-Link Corp. 802.11ac WLAN Adapter` and it works in AP mode but after some time I have `[WARNING][BB][halbb_get_fw_ra_rpt]Error macid = 11!!` in the kernel logs and the WIFI interface doesn't work anywmore. Only a reboot make it work again. This is on last debian stable.

**Comment by lwfinger** [comment]
That is the kind of problem that I cannot address. Post your problem on the Linux Wireless mailing list linux-wireless@vger.kernel.org.
