### ISSUE TITLE
warning: the compiler differs from the one used to build the kernel

### ISSUE THREAD

**Issue by Pang0512** [lwfinger/rtl8852au#75]
![Screenshot from 2024-01-08 01-21-40](https://github.com/lwfinger/rtl8852au/assets/155906869/47695469-9271-410d-9798-9826b15e9196)
Hi Larry, newbie here. I suffer the problem of compiler differs from the one used to build the kernel. The major problem is that the compiler is mark as x86_64, which is same as what I'm using but different name(AMD64). Is there any way to fix it? Cheers.

**Comment by lwfinger** [comment]
That is just a warning, not an error. It should not be a problem.
