### ISSUE TITLE
Adding an ipvlan link with the wireless device as the parent causes wifi to fail

### ISSUE THREAD

**Issue by Mossop** [lwfinger/rtl8852au#76]
I have the TP-Link Archer TX20U Plus and for normal use have the adapter working and connecting to the wifi just fine. However attempting to add an ipvlan link on top of it with `ip link add vlan0 link wlxf0a7314aaebc type ipvlan mode l2 bridge` causes the wifi to stop working. If it was previously connected then all connectivity is lost.  If it was not previously connected then `wpa_supplicant` reports a failure:

```
Jan 14 09:28:09 tikka wpa_supplicant[25443]: Successfully initialized wpa_supplicant
Jan 14 09:28:16 tikka wpa_supplicant[25443]: wifi0: Trying to associate with 74:83:c2:7a:cd:85 (SSID='****' freq=5500 MHz)
Jan 14 09:28:16 tikka wpa_supplicant[25443]: FT: Invalid key management type (2)
Jan 14 09:28:18 tikka wpa_supplicant[25443]: wifi0: Associated with ****
Jan 14 09:28:18 tikka wpa_supplicant[25443]: wifi0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
Jan 14 09:28:18 tikka wpa_supplicant[25443]: wifi0: CTRL-EVENT-REGDOM-CHANGE init=COUNTRY_IE type=COUNTRY alpha2=US
Jan 14 09:28:22 tikka wpa_supplicant[25443]: wifi0: CTRL-EVENT-DISCONNECTED bssid=**** reason=2
Jan 14 09:28:22 tikka wpa_supplicant[25443]: wifi0: WPA: 4-Way Handshake failed - pre-shared key may be incorrect
Jan 14 09:28:22 tikka wpa_supplicant[25443]: wifi0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="****" auth_failures=1 duration=10 reason=WRONG_KEY
Jan 14 09:28:22 tikka wpa_supplicant[25443]: BSSID **** ignore list count incremented to 2, ignoring for 10 seconds
```

This is using the same config as without the ipvlan link so the key should still be correct.

I've tested doing the same with a different wifi adapter (a Qualcomm Atheros AR93xx) and it works just fine. Is this something that would need to be fixed in the driver?

**Comment by lwfinger** [comment]
It is beyond my capacity to add new features to this driver. Sorry
