### ISSUE TITLE
module not working on 6.8.1 kernel

### ISSUE THREAD

**Issue by drjakub** [lwfinger/rtl8852au#88]
OpenSuse Tumbleweed recently updated their kernel to 6.8.1 and since then the module doesn't work, the module itself is building properly and installing but after restart there is no any wi-fi available. 

#rm -f .symvers.8852au
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.8.1-1-default/build M=/home/marek/Downloads/rtl8852au  modules
make[1]: Entering directory '/usr/src/linux-6.8.1-1-obj/x86_64/default'
make[1]: Leaving directory '/usr/src/linux-6.8.1-1-obj/x86_64/default'
#cp Module.symvers .symvers.8852au

install -p -m 644 8852au.ko  /lib/modules/6.8.1-1-default/kernel/drivers/net/wireless/realtek/rtw89/
/sbin/depmod -a 6.8.1-1-default

**Comment by lwfinger** [comment]
What led to your closing the issue? Did you find a problem?

I do not have an RTW8852AU, but my RTW8852BU works just fine with a fully updated openSUSE Tumbleweed.

**Comment by lwfinger** [comment]
What caused you to close this issue? Did you find a problem? It might be useful for others to see your solution.

I do not have an RTW8852AU, but I do have an RTW8852BU, which works perfectly on a completely-updated openSUSE Tumbleweed with kernel 6.8.1.

**Comment by drjakub** [comment]
i closed it because it was fault of my device, apparently it was hanged somehow, simple unplug and plug in again solve my issue and the device is working fine again. It was just coincidence that it happen the same day i updated kernel.
