### ISSUE TITLE
Build error with driver on debian sid with kernel 6.7.12

### ISSUE THREAD

**Issue by BranTregare** [lwfinger/rtl8852au#92]
amd64 platform:

full output of make command after git pull follows:

> user@hawkman:/home/user/src/rtl8852au# make
> #rm -f .symvers.8852au
> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.7.12-amd64/build M=/home/user/src/rtl8852au  modules
> make[1]: Entering directory '/usr/src/linux-headers-6.7.12-amd64'
>   CC [M]  /home/user/src/rtl8852au/os_dep/linux/ioctl_cfg80211.o
> /home/user/src/rtl8852au/os_dep/linux/ioctl_cfg80211.c:10255:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Werror=incompatible-pointer-types]
> 10255 |         .change_beacon = cfg80211_rtw_change_beacon,
>       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/user/src/rtl8852au/os_dep/linux/ioctl_cfg80211.c:10255:26: note: (near initialization for ‘rtw_cfg80211_ops.change_beacon’)
> /home/user/src/rtl8852au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_get_chbwoff_from_cfg80211_chan_def’:
> /home/user/src/rtl8852au/os_dep/linux/ioctl_cfg80211.c:6269:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
>  6269 |                 *ht = 0;
>       |                 ~~~~^~~
> /home/user/src/rtl8852au/os_dep/linux/ioctl_cfg80211.c:6271:9: note: here
>  6271 |         case NL80211_CHAN_WIDTH_20:
>       |         ^~~~
> cc1: some warnings being treated as errors
> make[3]: *** [/usr/src/linux-headers-6.7.12-common/scripts/Makefile.build:248: /home/user/src/rtl8852au/os_dep/linux/ioctl_cfg80211.o] Error 1
> make[2]: *** [/usr/src/linux-headers-6.7.12-common/Makefile:1936: /home/user/src/rtl8852au] Error 2
> make[1]: *** [/usr/src/linux-headers-6.7.12-common/Makefile:246: __sub-make] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-6.7.12-amd64'
> make: *** [Makefile:639: modules] Error 2
> user@hawkman:home/user/src/rtl8852au#

**Comment by BranTregare** [comment]
I do not know why there is a line through the copied output. it seems to complain about incompatible pointer types. Uhn it was the ~ symbol in the path. I have removed that and replaced it with full paths.

**Comment by lwfinger** [comment]
I had Debian Bookworm. After I had upgraded to Sid, I had kernel 6.8.9. The driver built correctly with that kernel, but with a kernel that new, the in-kernel driver works correctly and this repo is not needed.

**Comment by BranTregare** [comment]
Thank you for confirming that I no longer need to build this driver to get a working 8855au chipset on kernel 6.7.12 and above. I guess I need to look into the driver options in my kernel if the stock one does not work.

Also, thank you for maintaining this driver. I will try our the stock kernel without this driver and see if the Wi-Fi hardware initializes and works. Do you want confirmation of said test?
